server:
  port: 2003
spring:
  application:
    name: seata-account-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: e039ecd9-d1bb-490b-bc32-e8a5459bd89c
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.97.183:3306/seata_account
    username: root
    password: WG180cm.
#timed-out and no fallback available，failed and no fallback available 这个错误基本是出现在Hystrix熔断器 可以禁用feign的hystrix
feign:
  hystrix:
    enabled: false
  #但是这样不能解决根本问题，Feign调用远程服务时，默认为8秒超时时间，超时同样会跳转到熔断器进行处理。所以要从请求超时时间入手
  #ribbon:
  #ReadTimeout: 60000
  #ConnectTimeout: 60000

#====================================Seata Config===============================================
seata:
  enabled: true #是否开启spring-boot自动装配 自动代理数据源
  tx-service-group: seata_test_group # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  enable-auto-data-source-proxy: true #数据源自动代理开关（默认true开启）
  service:
    vgroup-mapping:
      seata_test_group: default # 需要与config.txt中的 service.vgroupMapping.seata_test_group=default 保持一致
    #grouplist:
    #  default: 127.0.0.1:8091
    disable-global-transaction: false
    registry:  ## 注册中心
      type: nacos #注册nacos
      nacos:
        application: seata-server  #nacos中seata-server启动注册成功后的服务名称
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        namespace: e039ecd9-d1bb-490b-bc32-e8a5459bd89c
        cluster: default
        username: nacos
        password: nacos
    config: ## 配置中心  与register.conf文件中的保持一致
      type: nacos
      nacos:
        server-addr: 127.0.0.1:8848
        #application: seata-server  #与register.conf文件中的保持一致
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
        namespace: e039ecd9-d1bb-490b-bc32-e8a5459bd89c #默认public，此处是创建的seata工作区间
  client:
    rm:
      report-success-enable: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml