server:
  port: 2002
spring:
  application:
    name: seata-storage-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.102.97.183:3306/seata_order
    username: root
    password: WG180cm.
#timed-out and no fallback available，failed and no fallback available 这个错误基本是出现在Hystrix熔断器 可以禁用feign的hystrix
feign:
  hystrix:
    enabled: false
  #但是这样不能解决根本问题，Feign调用远程服务时，默认为8秒超时时间，超时同样会跳转到熔断器进行处理。所以要从请求超时时间入手
  #ribbon:
  #ReadTimeout: 60000
  #ConnectTimeout: 60000

#====================================Seata Config===============================================
seata:
  enabled: true #是否开启spring-boot自动装配 自动代理数据源
  tx-service-group: wg_tx_group # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  client:
    #rm-report-success-enable: true #以下注释掉的1.0版本没有
    #rm-table-meta-check-enable: false # 自动刷新缓存中的表结构（默认false）
    rm-report-retry-count: 5 # 一阶段结果上报TC重试次数（默认5）
    rm-async-commit-buffer-limit: 10000 # 异步提交缓存队列长度（默认10000）
    rm:
      lock:
        lock-retry-internal: 10 # 校验或占用全局锁重试间隔（默认10ms）
        lock-retry-times: 30 # 校验或占用全局锁重试次数（默认30）
        lock-retry-policy-branch-rollback-on-conflict: true # 分支事务与其它全局回滚事务冲突时锁策略（优先释放本地锁让回滚成功）
    tm-commit-retry-count: 3 # 一阶段全局提交结果上报TC重试次数（默认1次，建议大于1）
    tm-rollback-retry-count: 3 # 一阶段全局回滚结果上报TC重试次数（默认1次，建议大于1）
    undo:
      undo-data-validation: true # 二阶段回滚镜像校验（默认true开启）
      undo-log-serialization: jackson # undo序列化方式（默认jackson）
      undo-log-table: undo_log  # 自定义undo表名（默认undo_log）
    log:
      exceptionRate: 100 # 日志异常输出概率（默认100）
    support:
      spring:
        datasource-autoproxy: true #数据源自动代理开关（默认false关闭）
  service:
    vgroup-mapping:
      wg_tx_group: default # TC 集群（必须与seata-server保持一致）
    #enable-degrade: false # 降级开关
    disable-global-transaction: false # 禁用全局事务（默认false）
    grouplist:
      default: 127.0.0.1:8091
  transport:
    #shutdown:
    #wait: 3
    #thread-factory:
    #boss-thread-prefix: NettyBoss
    #worker-thread-prefix: NettyServerNIOWorker
    #server-executor-thread-prefix: NettyServerBizHandler
    #share-boss-worker: false
    #client-selector-thread-prefix: NettyClientSelector
    #client-selector-thread-size: 1
    #client-worker-thread-prefix: NettyClientWorkerThread
    #type: TCP
    #server: NIO
    heartbeat: true #client和server通信心跳检测开关	默认true开启
    serialization: seata #client和server通信编解码方式	seata（ByteBuf）、protobuf、kryo、hession，默认seata
    compressor: none #client和server通信数据压缩方式	none、gzip，默认none
    enable-client-batch-send-request: true # 客户端事务消息请求是否批量合并发送（默认true）
  registry:
    file:
      name: file.conf
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace:
      cluster: default
  config:
    file:
      name: file.conf
    type: nacos
    nacos:
      namespace:
      server-addr: localhost:8848

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml