server:
  port: 8801
spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #标识定义的名称，用于binding整合
          type: rabbit #消息组件的类型
          environment: #设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 47.102.47.99
                port: 5672
                username: admin
                password: admin
      bindings: #服务的整合处理
        output: #表示该服务是个消息生产者（发送端）这个名字是一个通道channel的名称
          destination: wwgExchange #表示要使用的exchange（交换机）（类似于kafka的topic发布主题）名称定义
          content-type: application/json #设置消息类型，本次为json，文本侧设置"text/plain"
          binder: defaultRabbit #设置要绑定的消息服务的具体设置

eureka:
  client:
    service-url: #客户端进行eureka注册的配置
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔（默认是30秒钟）
    lease-expiration-duration-in-seconds: 5 #eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除服务
