server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #将微服务nacos-order-consumer注册进nacos
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次扫描，直至找到未被占用的端口
        prot: 8719
#消费者将要去访问的微服务名称（成功注册进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider
#激活sentinel对Feign的支持
feign:
  sentinel:
    enabled: false