server:
  port: 9527

spring:
  application:
    name: cloud-zuul-gateway9527

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群版
    register-with-eureka: true #zuul作为路由网关需要将自己注册进eureka
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
  instance:
    instance-id: gateway9527.com
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1 #eureka客户端向服务注册中心发送心跳间隔
    lease-expiration-duration-in-seconds: 2 #eureka服务注册中心在收到最后一次心跳后等待时间，超时将剔除服务

#网关路由映射规则
zuul:
  routes:
    mydept.serviceId: colud-payment-service #注册进eureka中的微服务实例名称
    mydept.path: /payment8001/** #以后就通过这个映射的服务名去访问微服务下的方法
  #ignored-services: colud-payment-service #遵循单入口 单出口原则 使通过微服务实例名称不能访问
  ignored-services: "*" #忽略多个微服务实例名称访问入口
  prefix: /wen #增加统一的访问前缀