server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route1 #路由的id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://colud-payment-service #匹配后提供服务的路由地址 http协议替换为lb协议,标识启用gateway的负载均衡功能
                                          #lb://serviceName是spring cloud gateway在微服务中自动为我们创建的负载均衡uri
          predicates:
            - Path=/payment/getServerPort #断言 （类似于sql比较结果 求真值，布尔表达式 true或者false）这里就是路径相匹配的进行路由

        - id: payment_route2 #路由的id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://colud-payment-service #匹配后提供服务的路由地址 http协议替换为lb协议,标识启用gateway的负载均衡功能
                                          #lb://serviceName是spring cloud gateway在微服务中自动为我们创建的负载均衡uri
          predicates:
            - Path=/payment/getPaymentById/** #断言 （类似于sql比较结果，sql是没有bool类型的，求真值，可以认为是布尔表达式 true或者false） 这里就是路径相匹配的进行路由
            #- After=2021-07-15T14:19:33.950+08:00[Asia/Shanghai] #断言 在这个时间之前是可以访问的
            #- Before=2021-07-15T14:19:33.950+08:00[Asia/Shanghai] #断言 在这个时间之后是可以访问网关路由的
            #- Between=2021-07-15T14:19:33.950+08:00[Asia/Shanghai],2021-07-15T15:45:33.950+08:00[Asia/Shanghai] #断言 在这个时间区间是可以访问网关路由的
            #- Cookie=username,zsmx
            - Header=X-Request-Id,\d+ #请求头要有X-Request-Id属性并且值为整数的正则表达式
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka/
